apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdlc
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/eti-codefresh/gdlc-gs.git
      path: .
      targetRevision: main
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: akav-kind-namespace-2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
