apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: akavalchuk-local-helm-runtime-mac
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {akavalchuk-local-helm-runtime-mac/akavalchuk-local-helm-runtime-mac.yaml,akavalchuk-local-helm-runtime-mac/helm-gs.yaml,all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,runtimes/akavalchuk-local-helm-runtime-mac/**/*.yaml,runtimes/akavalchuk-local-helm-runtime-mac/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/akavalchuk/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
