apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: demo-multiapp
spec:
  promotionFlows:
    - name: demo-pf-multiapp
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - promotion*
