apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: guestbook-4
spec:
  promotionFlows:
    - name: stage-prod
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - del
  concurrency: queue
