apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: my-product
spec:
  promotionFlows:
    - name: manual-test
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - promotion
