apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: my-product
spec:
  promotionFlows:
    - name: no-pf-test
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - test-empty
    - name: bruh
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - bruh
  promotionTemplate:
    versionSource:
      file: guestbook-ui-deployment.yaml
      jsonPath: metadata.labels.version
    promotion:
      guestbook-ui-deployment.yaml:
        jsonPaths:
          - $.*.*.*.*.*.image
  concurrency: terminate
