apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: my-product
spec:
  promotionFlows:
    - name: stg-prod
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - test*
  promotionTemplate:
    versionSource:
      file: guestbook-ui-deployment.yaml
      jsonPath: $.*.*.version
  concurrency: queue
