apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: my-product
spec:
  promotionTemplate:
    versionSource:
      file: guestbook-ui-deployment.yaml
      jsonPath: $.*.*.version
  concurrency: queue
