apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: qqqqqq
spec:
  promotionFlows:
    - name: bruh
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - testing
  concurrency: terminate
