apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: relative-files
spec:
  promotionFlows:
    - name: bruh
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - outside
  promotionTemplate:
    promotion:
      ../file.yaml:
        jsonPaths:
          - $.image.tag
      guestbook-ui-deployment.yaml:
        jsonPaths:
          - $.spec.template.spec.containers['0'].image
  concurrency: terminate
