apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: sbx3-test
spec:
  promotionFlows:
    - name: no-pf-test
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - test
  concurrency: queue
