apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: simple-product
spec:
  promotionFlows:
    - name: s-t3-p
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - test-empty
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.*.tag
  concurrency: queue
