apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: test
spec:
  promotionTemplate:
    promotion:
      guestbook-ui-deployment.yaml:
        jsonPaths:
          - $.*.*.version
      guestbook-ui-svc.yaml:
        jsonPaths:
          - $.*.*.*.port
  concurrency: queue
