apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akavalchuk-local-helm-runtime-kim-default-git-source
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/akavalchuk/local-gs-kim.git
    path: .
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: akavalchuk-local-helm-runtime-kim
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
