apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akavalchuk-local-helm-runtime-kim
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/akavalchuk/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
    path: resources/akavalchuk-local-helm-runtime-kim/chart
    helm:
      releaseName: akavalchuk-local-helm-runtime-kim
  destination:
    namespace: akavalchuk-local-helm-runtime-kim
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
