apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: bruh
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: test8
    - environment: test-2
      dependsOn:
        - production
      policy:
        action: commit
        preAction: test8
