apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: default-generated-promotion-flow
  annotations:
    description: promotion flow that was generated as part of promotion on boarding
spec:
  triggerEnvironment: dev
  steps:
    - environment: staging
      dependsOn:
        - dev
      policy:
        action: commit
        preAction: pre-action
        postAction: post-action
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: pre-action
        postAction: post-action
