apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: dev-prod
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: production
      dependsOn:
        - dev
      policy:
        action: commit
