apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: empty-env
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: empty
      dependsOn:
        - staging
      policy:
        action: commit
    - environment: production
      dependsOn:
        - empty
      policy:
        action: commit
