apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: exit1-post-action
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        postAction: simple-failure
