apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: final-hook-move-test
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: pr
      hooks:
        onStart: test4
        onSuccess: test5
        onFail: test8
  hooks:
    onStart: test4
    onSuccess: test8
    onFail: test4
