apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action
spec:
  entrypoint: create-jira-ticket
  templates:
  - name: create-jira-ticket
    container:
      image: curlimages/curl:7.85.0
      command: [sh, -c]
      # Reads Jira info from /mnt/secret and creates a Jira ticket
      args:
      - |
        JIRA_URL=$(cat /mnt/secret/jira_url)
        JIRA_USER=$(cat /mnt/secret/jira_user)
        JIRA_TOKEN=$(cat /mnt/secret/jira_token)
        JIRA_PROJECT=$(cat /mnt/secret/jira_project)
        AUTH=$(echo -n "$JIRA_USER:$JIRA_TOKEN" | base64)
        PAYLOAD=$(jq -n \
          --arg proj "$JIRA_PROJECT" \
          --arg summary "Auto-created ticket" \
          --arg description "Ticket created by Argo workflow pre-action" \
          '{fields: {project: {key: $proj}, summary: $summary, description: $description, issuetype: {name: "Task"}}}')
        curl -s -X POST "$JIRA_URL/rest/api/2/issue" \
          -H "Authorization: Basic $AUTH" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD"
      volumeMounts:
      - name: jira-secret
        mountPath: /mnt/secret
        readOnly: true
    volumes:
    - name: jira-secret
      secret:
        secretName: jira-auth-secret

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-action
spec:
  entrypoint: send-slack-message
  templates:
  - name: send-slack-message
    container:
      image: curlimages/curl:7.85.0
      command: [sh, -c]
      args:
      - |
        WEBHOOK_URL=$(cat /mnt/secret/slack_webhook_url)
        PAYLOAD='{"text": "Post-action workflow completed successfully."}'
        curl -s -X POST "$WEBHOOK_URL" -H 'Content-Type: application/json' -d "$PAYLOAD"
      volumeMounts:
      - name: slack-secret
        mountPath: /mnt/secret
        readOnly: true
    volumes:
    - name: slack-secret
      secret:
        secretName: slack-webhook-secret