apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action
spec:
  entrypoint: create-jira-ticket
  templates:
  - name: create-jira-ticket
    container:
      image: curlimages/curl:7.78.0
      command: ["/bin/sh", "-c"]
      envFrom:
        - secretRef:
            name: jira-auth
      env:
        - name: JIRA_URL
          valueFrom:
            secretKeyRef:
              name: jira-auth
              key: url
        - name: JIRA_PROJECT_KEY
          valueFrom:
            secretKeyRef:
              name: jira-auth
              key: projectKey
        - name: JIRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: jira-auth
              key: username
        - name: JIRA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: jira-auth
              key: apiToken
      args:
        - |
          curl -X POST \
            -H "Content-Type: application/json" \
            -u ${JIRA_USERNAME}:${JIRA_API_TOKEN} \
            -d "{\"fields\":{\"project\":{\"key\":\"${JIRA_PROJECT_KEY}\"},\"summary\":\"Automated ticket from Argo Workflow\",\"description\":\"This ticket was created by Argo Workflow pre-action\",\"issuetype\":{\"name\":\"Task\"}}}" \
            ${JIRA_URL}/rest/api/2/issue

---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-action
spec:
  entrypoint: send-slack-message
  templates:
  - name: send-slack-message
    container:
      image: curlimages/curl:7.78.0
      command: ["/bin/sh", "-c"]
      envFrom:
        - secretRef:
            name: slack-webhook
      env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook
              key: webhookUrl
      args:
        - |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"Automated notification from Argo Workflow post-action"}' \
            ${SLACK_WEBHOOK_URL}