apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action
  annotations:
    codefresh.io/workflow-origin: promotion
spec:
  entrypoint: create-jira-ticket
  templates:
  - name: create-jira-ticket
    container:
      image: curlimages/curl:7.85.0
      command: [sh, -c]
      args:
      - |
        JIRA_USER=$(kubectl get secret jira-credentials -n ${APP_NAMESPACE} -o jsonpath='{.data.username}' | base64 --decode)
        JIRA_TOKEN=$(kubectl get secret jira-credentials -n ${APP_NAMESPACE} -o jsonpath='{.data.token}' | base64 --decode)
        JIRA_URL="https://your-jira-instance.atlassian.net/rest/api/2/issue"
        PAYLOAD=$(jq -n \
          --arg project "PROJ" \
          --arg summary "Release ${RELEASE_ID} for ${APP_NAME}" \
          --arg description "Promotion flow: ${PROMOTION_FLOW_NAME}\nApp: ${APP_NAME}\nNamespace: ${APP_NAMESPACE}\nRepo: ${REPO_URL}\nBranch: ${BRANCH}\nPath: ${PATH}\nProduct: ${PRODUCT_NAME}" \
          --arg issuetype "Task" \
          '{fields: {project: {key: $project}, summary: $summary, description: $description, issuetype: {name: $issuetype}}}')
        ISSUE_KEY=$(curl -s -X POST -u $JIRA_USER:$JIRA_TOKEN -H "Content-Type: application/json" --data "$PAYLOAD" $JIRA_URL | jq -r .key)
        echo $ISSUE_KEY > /tmp/issue_key.txt
    outputs:
      parameters:
      - name: issue-key
        valueFrom:
          path: /tmp/issue_key.txt
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-action
  annotations:
    codefresh.io/workflow-origin: promotion
spec:
  entrypoint: close-jira-ticket
  templates:
  - name: close-jira-ticket
    inputs:
      parameters:
      - name: issue-key
    container:
      image: curlimages/curl:7.85.0
      command: [sh, -c]
      args:
      - |
        JIRA_USER=$(kubectl get secret jira-credentials -n ${APP_NAMESPACE} -o jsonpath='{.data.username}' | base64 --decode)
        JIRA_TOKEN=$(kubectl get secret jira-credentials -n ${APP_NAMESPACE} -o jsonpath='{.data.token}' | base64 --decode)
        TRANSITION_URL="https://your-jira-instance.atlassian.net/rest/api/2/issue/{{inputs.parameters.issue-key}}/transitions"
        TRANSITION_PAYLOAD='{"transition": {"id": "31"}}'
        # transition id 31 assumed to be "Done", adjust according to your Jira config
        curl -s -X POST -u $JIRA_USER:$JIRA_TOKEN -H "Content-Type: application/json" -d "$TRANSITION_PAYLOAD" "$TRANSITION_URL"