apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-action
  annotations:
    codefresh.io/workflow-origin: promotion
    version: 0.0.1
spec:
  arguments:
    parameters:
      - name: APP_NAMESPACE
      - name: APP_NAME
      - name: REPO_URL
      - name: BRANCH
      - name: PATH
      - name: COMMIT_SHA
        value: ''
      - name: COMMIT_MESSAGE
        value: ''
      - name: COMMIT_AUTHOR
        value: ''
      - name: COMMIT_DATE
        value: ''
      - name: PRODUCT_NAME
      - name: APP_VERSION
      - name: PROMOTION_FLOW_NAME
      - name: RELEASE_ID
      - name: JIRA_ISSUE_KEY
  entrypoint: main-workflow
  templates:
    - name: main-workflow
      steps:
        - - name: close-jira-ticket
            template: close-jira-ticket

    - name: close-jira-ticket
      retryStrategy:
        limit: "5"
        retryPolicy: "Always"
        backoff:
          duration: "10s"
      inputs:
        parameters:
          - name: JIRA_ISSUE_KEY
      container:
        image: curlimages/curl:7.85.0
        command:
          - sh
          - -c
        args:
          - |
            echo "Closing Jira ticket {{inputs.parameters.JIRA_ISSUE_KEY}} with status Done"
            JIRA_BASE_URL="https://your-jira-instance.atlassian.net"
            JIRA_USER=$(cat /secrets/jira-username)
            JIRA_API_TOKEN=$(cat /secrets/jira-api-token)

            TRANSITION_ID_DONE="31"
            # The transition ID might vary; adjust it according to your Jira workflow

            RESPONSE=$(curl -s -u "$JIRA_USER:$JIRA_API_TOKEN" -X POST \
              --data "{\"transition\":{\"id\":\"$TRANSITION_ID_DONE\"}}" \
              -H "Content-Type: application/json" \
              $JIRA_BASE_URL/rest/api/2/issue/{{inputs.parameters.JIRA_ISSUE_KEY}}/transitions)
            if echo "$RESPONSE" | grep -q "errors"; then
              echo "Failed to close Jira issue: $RESPONSE"
              exit 1
            fi
            echo "Jira issue {{inputs.parameters.JIRA_ISSUE_KEY}} closed with status Done"
      volumeMounts:
        - name: jira-credentials
          mountPath: /secrets
          readOnly: true
  volumes:
    - name: jira-credentials
      secret:
        secretName: jira-credentials