apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: hooks-test
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: pr
      onFail: test9
      onStart: test7
      onSuccess: test8
  onStart: test4
  onSuccess: test5
  onFail: test6
