apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: hooks-test-2
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: test7
        postAction: test7
      hooks:
        onFail: test9
        onStart: test7
        onSuccess: test8
  hooks:
    onStart: test4
    onSuccess: test5
    onFail: test6
