apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: long-wait
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: test7
