apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: no-pf-test
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
