apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: p-t3
  annotations:
    description: ""
spec:
  triggerEnvironment: production
  steps:
    - environment: test-3
      dependsOn:
        - production
      policy:
        action: commit
