apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: paralel-suspend-and-failure
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: pr
        postAction: akav-suspend-pw-1
    - environment: production-2
      dependsOn:
        - staging
      policy:
        action: pr
