apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: pf-stg-to-test
  annotations:
    description: ""
spec:
  triggerEnvironment: namespace-staging
  steps:
    - environment: test
      dependsOn:
        - namespace-staging
      policy:
        action: commit
