apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: scotts-promotion-flow
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: production
      dependsOn:
        - dev
      policy:
        action: commit
  hooks:
    onStart: scotts-wf
    onSuccess: scotts-wf
    onFail: scotts-wf
