apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: simple-success-post-pre-pr
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: pr
        preAction: simple-success-1
        postAction: simple-success-1
