apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: stg-prod-policy
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
