apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: stg-prod-failure
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: simple-failure-1
        postAction: simple-failure-1
