apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: stg-prod-actions
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: simple-success-1
        postAction: simple-success-1
