apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: test-with-post-trigger
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: production
      dependsOn:
        - staging
      policy:
        action: pr
    - environment: test-3
      dependsOn:
        - staging
      policy:
        action: commit
    - environment: test-2
      dependsOn:
        - test-3
      policy:
        action: pr
    - environment: akav-2
      dependsOn:
        - staging
      policy:
        action: commit
    - environment: akav-3
      dependsOn:
        - akav-2
      policy:
        action: commit
  postTrigger: test2
