# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: akav-suspend-pw-2
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
    description: suspend as child pw
spec:
  serviceAccountName: cf-default-promotion-workflows-sa
  entrypoint: run-tests-and-suspend
  templates:
    - name: run-tests-and-suspend
      dag:
        tasks:
          - name: echo
            templateRef:
              name: simple-success-1
              template: simple-success
          - name: suspend
            templateRef:
              name: akav-suspend-pw
              template: suspend-promotion