apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-runtime-eti-0
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/akavalchuk/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
    path: resources/demo-runtime-eti-0/chart
    helm:
      releaseName: demo-runtime-eti-0
  destination:
    namespace: demo-runtime-eti-0
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
