apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: sbx3-test
spec:
  project: default
  destination:
    name: in-cluster
    namespace: staging
  source:
    path: guestbook
    repoURL: https://github.com/akavalchuk/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
