apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: akavalchuk-sbx-3-helm-runtime-5
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {akavalchuk-sbx-3-helm-runtime-5/akavalchuk-sbx-3-helm-runtime-5.yaml,akavalchuk-sbx-3-helm-runtime-5/test.yaml,all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,configurations/**/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,runtimes/akavalchuk-sbx-3-helm-runtime-5/**/*.yaml,runtimes/akavalchuk-sbx-3-helm-runtime-5/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/akavalchuk/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
