gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io,https://akavalchuk-platform.ngrok.io
      graphqlPlayground: 'true'
    image:
      pullPolicy: Always
      tag: 1.2657.1-cr-22414-call-platform-d3241ec
  global:
    codefresh:
      url: https://akavalchuk-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - akavalchuk-local.rnd-sandbox.cf-infra.com
        protocol: https
      name: akavalchuk-local-helm-runtime
  installer:
    skipValidation: true
