apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: localfresh-runtime-20-11-23-1
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/localfresh-runtime-20-11-23-1/*.yaml,runtimes/localfresh-runtime-20-11-23-1/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml,localfresh-runtime-20-11-23-1/cf-gitops-runtime.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/akavalchuk/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
