gitops-runtime:
  gitops-operator:
    env:
      GITOPS_OPERATOR_VERSION: 0.7.9
    image:
      pullPolicy: Always
      tag: cr-29261-86428d8
  app-proxy:
    image:
      repository: quay.io/codefresh/dev/cap-app-proxy
      tag: 1.3532.0-cr-29250-spare-b48efb4
    config:
      cors: http://local.codefresh.io,https://akavalchuk-platform.ngrok.io
      graphqlPlayground: 'true'
    image:
      # tag: 1.3228.0
      pullPolicy: Always
  global:
    codefresh:
      url: https://akavalchuk-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - akavalchuk-local.rnd-sandbox.cf-infra.com
        protocol: https
      name: akav-demo-helm-runtime-2
      isConfigurationRuntime: true
  installer:
    skipValidation: true
