gitops-runtime:
  gitops-operator:
    image:
      tag: v0.3.16
  app-proxy:
    image:
      tag: 1.3146.0
      pullPolicy: Always
    config:
      cors: http://local.codefresh.io,https://akavalchuk-platform.ngrok.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      url: https://akavalchuk-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - akavalchuk-local.rnd-sandbox.cf-infra.com
        protocol: https
      name: akav-demo-helm-runtime-2
      isConfigurationRuntime: true
  installer:
    skipValidation: true
