gitops-runtime:
  app-proxy:
    config:
      cors: >-
        http://local.codefresh.io,https://akavalchuk-platform.ngrok.io,https://g.codefresh.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      url: https://g.codefresh.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - alex-kavalchuk-demo.rnd-sandbox.cf-infra.com
        protocol: https
      name: akav-demo-helm-runtime-2
      isConfigurationRuntime: true
  installer:
    skipValidation: true
