apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: test-policy
spec:
  priority: 1
  selector:
    product:
      names:
        - simple-product
        - my-product
    targetEnvironment:
      names:
        - production
  policy:
    action: commit
    preAction: simple-success-1
    postAction: simple-success-1
