apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aliaksandr-kavalchuk-codefresh-io-akav-demo-eks-cluste-rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: csdp
  source:
    chart: argo-rollouts
    repoURL: https://codefresh-io.github.io/argo-helm
    targetRevision: 2.22.1-1-cap-sw
    helm:
      releaseName: argo-rollouts
  destination:
    namespace: default
    server: https://1DB7335DE0C90B4140866A530BFA25F4.gr7.us-east-1.eks.amazonaws.com
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
