apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aliaksandr-kavalchuk-codefresh-io-akav-demo-us-east-1--rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: csdp
  source:
    repoURL: https://github.com/codefresh-io/csdp-official.git
    path: csdp/base/argo-rollouts
    targetRevision: latest-managed
  destination:
    namespace: default
    server: https://9166D425420BA49B403F0594EC47A9AE.gr7.us-east-1.eks.amazonaws.com
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
