gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io,https://akavalchuk-platform.ngrok.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      accountId: 669e06746fdd1cfa04f44e47
      url: https://akavalchuk-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        enabled: false
      ingressUrl: http://host.docker.internal:8080
      isConfigurationRuntime: true
      name: akav-demo-kind-runtime-1
  installer:
    skipValidation: true
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
