gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io,https://akavalchuk-platform.ngrok.io
      graphqlPlayground: 'true'
  global:
    codefresh:
      url: https://akavalchuk-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        className: nginx-public
        enabled: true
        hosts:
          - akavalchuk-local.rnd.sandbox.codefresh.io
        protocol: https
      name: akavalchuk-local-helm-runtime-kim
  installer:
    skipValidation: true
