apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: echo-4
  labels:
    codefresh.io/promotion: 'true'
  annotations:
    version: 0.0.1
    description: testing copy
spec:
  arguments:
    parameters:
      - name: message
  entrypoint: echo
  podGC:
    strategy: OnWorkflowCompletion
  serviceAccountName: codefresh-sa
  templates:
    - container:
        args:
          - '{{inputs.parameters.message}}'
        command:
          - sleep 10 && exit 1
        image: alpine
        name: ''
        resources: {}
      inputs:
        parameters:
          - name: message
            value: hello world
      metadata: {}
      name: echo
      outputs: {}
