# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test9
  annotations:
    description: m
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
spec:
  arguments:
    parameters:
      - name: message
        value: hi
  entrypoint: gen-random-int
  podGC:
    strategy: OnWorkflowCompletion
  serviceAccountName: codefresh-sa
  templates:
    - name: gen-random-int
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import random
          i = random.randint(0, 1)
          exit(i)
